
[cursor.vi_mode_style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "MesloLGMDZ Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGMDZ Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGMDZ Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
startup_mode = "Maximized"
blur = true
opacity = 0.7



[window.padding]
x = 10
y = 10

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
